[package]
name = "png2webp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.91"
image = "0.24.9"

[lib]
crate-type = ["cdylib", "rlib"]